/-
Copyright (c) 2026. All rights reserved.
Author: Julián Calderón Almendros
License: MIT
-/

-- Root module: auto-generated by gen-root.bash
-- Uses barrel imports for subdirectories (see AI-GUIDE.md §23, §30–33).
-- Run 'bash gen-root.bash' after adding or removing modules.

import FOL.FOL
import FOL.Soundness
import FOL.Computability.Turing
import FOL.Extensions.Classical
import FOL.MetaTheory.Compactness
import FOL.MetaTheory.Completeness
import FOL.MetaTheory.Soundness
import FOL.Metamath.Consistency
import FOL.Metamath.Independence
import FOL.ModelTheory.Basic
import FOL.ProofSystem.Deduction
import FOL.Semantics.Basic
import FOL.Syntax.Basic
import FOL.Tactics.Basic
import FOL.Tactics.Solver
import FOL.TextSyntax.Basic
import FOL.Theorems.Deduction
import FOL.Theorems.Derived
import FOL.Theorems.FOL.Eq
import FOL.Theorems.FOL.Quantifiers
import FOL.Theorems.Prop.Impl
import FOL.Theorems.Prop.Neg
import FOL.Theorems.Soundness
