#!/bin/bash
# gen-root.bash — Regenerate root ProjectName.lean with barrel-aware imports
#
# Usage: bash gen-root.bash
#
# Scans ProjectName/ for all .lean files (excluding _template.lean and test files).
# If a subdirectory has a barrel file (e.g., CList.lean for CList/), the root
# imports only the barrel instead of listing each sub-module individually.
# This follows the export/glob pattern defined in AI-GUIDE.md §17-18.

set -e

# Detect project name from lakefile.lean
# Supports both «Name» and "Name" syntax; prefers lean_lib (correct case) over package
PROJECT_NAME=$(grep -E 'lean_lib\s+«([^»]+)»' lakefile.lean 2>/dev/null | sed 's/.*«\(.*\)».*/\1/' | head -1)
if [ -z "$PROJECT_NAME" ]; then
    PROJECT_NAME=$(grep -E '^lean_lib\s+"([^"]+)"' lakefile.lean 2>/dev/null | sed 's/.*"\(.*\)".*/\1/' | head -1)
fi
if [ -z "$PROJECT_NAME" ]; then
    PROJECT_NAME=$(grep -E 'package\s+«([^»]+)»' lakefile.lean 2>/dev/null | sed 's/.*«\(.*\)».*/\1/' | head -1)
fi
if [ -z "$PROJECT_NAME" ]; then
    PROJECT_NAME=$(grep -E '^package\s+"([^"]+)"' lakefile.lean 2>/dev/null | sed 's/.*"\(.*\)".*/\1/' | head -1)
fi
if [ -z "$PROJECT_NAME" ]; then
    echo "Error: Could not detect project name from lakefile.lean"
    exit 1
fi

ROOT_FILE="${PROJECT_NAME}.lean"
MODULE_DIR="${PROJECT_NAME}"
YEAR=$(date +%Y)
AUTHOR=$(git config user.name 2>/dev/null || echo "Your Name")

# Collect barrel-covered subdirectories
declare -A BARREL_DIRS
for BARREL in "${MODULE_DIR}"/*.lean; do
    [ ! -f "$BARREL" ] && continue
    BASENAME=$(basename "$BARREL" .lean)
    # Skip _template and test files
    [[ "$BASENAME" == _* ]] && continue
    [[ "$BASENAME" == test* ]] && continue
    [[ "$BASENAME" == Test* ]] && continue
    # If a directory with the same name exists, this is a barrel file
    if [ -d "${MODULE_DIR}/${BASENAME}" ]; then
        BARREL_DIRS["${BASENAME}"]=1
    fi
done

# Collect imports: barrel files for subdirectories, individual files for top-level
IMPORTS=()

# First: barrel imports (sorted)
for DIR_NAME in $(echo "${!BARREL_DIRS[@]}" | tr ' ' '\n' | sort); do
    IMPORTS+=("${PROJECT_NAME}.${DIR_NAME}")
done

# Second: top-level .lean files that are NOT barrels, NOT _template, NOT test files
while IFS= read -r FILE; do
    BASENAME=$(basename "$FILE" .lean)
    [ "$BASENAME" = "_template" ] && continue
    [[ "$BASENAME" == test* ]] && continue
    [[ "$BASENAME" == Test* ]] && continue
    # Skip if this is a barrel file (already included above)
    [ "${BARREL_DIRS[$BASENAME]+exists}" ] && continue
    IMPORT_NAME="${PROJECT_NAME}.${BASENAME}"
    IMPORTS+=("$IMPORT_NAME")
done < <(find "$MODULE_DIR" -maxdepth 1 -name "*.lean" | sort)

# Third: files in subdirectories WITHOUT a barrel (sorted)
while IFS= read -r SUBDIR; do
    DIR_NAME=$(basename "$SUBDIR")
    # Skip if this subdirectory has a barrel
    [ "${BARREL_DIRS[$DIR_NAME]+exists}" ] && continue
    while IFS= read -r FILE; do
        BASENAME=$(basename "$FILE" .lean)
        [ "$BASENAME" = "_template" ] && continue
        [[ "$BASENAME" == test* ]] && continue
        [[ "$BASENAME" == Test* ]] && continue
        REL="${FILE#${MODULE_DIR}/}"
        REL="${REL%.lean}"
        IMPORT_NAME="${PROJECT_NAME}.${REL//\//.}"
        IMPORTS+=("$IMPORT_NAME")
    done < <(find "$SUBDIR" -name "*.lean" | sort)
done < <(find "$MODULE_DIR" -mindepth 1 -maxdepth 1 -type d | sort)

if [ ${#IMPORTS[@]} -eq 0 ]; then
    echo "Warning: No modules found in $MODULE_DIR/"
fi

# Unlock root if locked
WAS_LOCKED=false
if grep -Fxq "$ROOT_FILE" locked_files.txt 2>/dev/null; then
    WAS_LOCKED=true
    bash git-lock.bash unlock "$ROOT_FILE"
fi

# Write root file
{
    echo "/-"
    echo "Copyright (c) ${YEAR}. All rights reserved."
    echo "Author: ${AUTHOR}"
    echo "License: MIT"
    echo "-/"
    echo ""
    echo "-- Root module: auto-generated by gen-root.bash"
    echo "-- Uses barrel imports for subdirectories (see AI-GUIDE.md §17-18)."
    echo "-- Run 'bash gen-root.bash' after adding or removing modules."
    echo ""
    for IMPORT in "${IMPORTS[@]}"; do
        echo "import ${IMPORT}"
    done
} > "$ROOT_FILE"

# Report
BARREL_COUNT=${#BARREL_DIRS[@]}
echo "✅ Generated $ROOT_FILE with ${#IMPORTS[@]} imports (${BARREL_COUNT} barrel(s)):"
for IMPORT in "${IMPORTS[@]}"; do
    # Mark barrel imports
    SHORTNAME="${IMPORT#${PROJECT_NAME}.}"
    if [ "${BARREL_DIRS[$SHORTNAME]+exists}" ]; then
        echo "   $IMPORT  (barrel)"
    else
        echo "   $IMPORT"
    fi
done

# Re-lock if it was locked
if [ "$WAS_LOCKED" = true ]; then
    bash git-lock.bash lock "$ROOT_FILE"
fi
